# Generated by Django 3.2.6 on 2021-08-17 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Pets Name')),
                ('age', models.PositiveIntegerField(db_index=True, default=0, null=True, verbose_name='Age')),
                ('come_data', models.DateTimeField(auto_now_add=True)),
                ('weight', models.PositiveIntegerField(db_index=True, null=True, verbose_name='Weight')),
                ('special_signs', models.TextField(blank=True, max_length=100, null=True, verbose_name='Special signs')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Surname')),
                ('phone', models.IntegerField(db_index=True, null=True, verbose_name='Phone')),
                ('mail', models.EmailField(db_index=True, max_length=254, null=True, verbose_name='Mail')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
