# Generated by Django 3.2.6 on 2021-08-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profiles', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='app_pets.profile', verbose_name='Shelter'),
        ),
    ]
